<<<<<<< HEAD
uuid: 884be2e0-ca33-4732-8eef-f04b3282de49
=======
uuid: 3c5c2176-cd20-4836-9236-c0dcf1e78bc8
>>>>>>> 0a3fac84826d2126349f1954e94f5ac86547d8df
langcode: en
status: true
dependencies:
  theme:
    - laujutheme
_core:
  default_config_hash: 7rR9chwXvdM2H8OYMAYx9Zj3GGlPMrZp_M3ZA4thYTk
id: laujutheme_page_title
theme: laujutheme
region: content
weight: -50
provider: null
plugin: page_title_block
settings:
  id: page_title_block
  label: 'Page title'
  provider: core
  label_display: '0'
visibility: {  }
