<<<<<<< HEAD
uuid: 16440a47-563a-4147-b7b5-6fd2c1a9d9de
=======
uuid: 94cf81f7-a10a-4531-86f9-72bd8109108a
>>>>>>> 0a3fac84826d2126349f1954e94f5ac86547d8df
langcode: en
status: true
dependencies:
  config:
    - system.menu.footer
  module:
    - system
  theme:
    - laujutheme
_core:
  default_config_hash: 8zRjTNbfNAJ94lQpZDu6MkyD87GYJ2zpH9VQPVmRbcM
id: laujutheme_footer
theme: laujutheme
region: header
weight: 0
provider: null
plugin: 'system_menu_block:footer'
settings:
  id: 'system_menu_block:footer'
  label: 'Footer menu'
  provider: system
  label_display: '0'
  level: 1
  depth: 0
  expand_all_items: false
visibility: {  }
