<<<<<<< HEAD
uuid: a245455f-da71-4ea8-bf48-a1f4785042cd
=======
uuid: d4c89bb9-b48c-47df-9335-336688469e68
>>>>>>> 0a3fac84826d2126349f1954e94f5ac86547d8df
langcode: en
status: true
dependencies:
  module:
    - search
  theme:
    - laujutheme
_core:
  default_config_hash: za-39d5WDUg6XvbyqSnuVYEeq6QM4qKJxW8MnoAha5A
id: laujutheme_search
theme: laujutheme
region: sidebar_first
weight: -1
provider: null
plugin: search_form_block
settings:
  id: search_form_block
  label: Search
  provider: search
  label_display: visible
visibility: {  }
