<<<<<<< HEAD
uuid: 9a6db796-6849-456c-b5fa-f8abed4417e7
=======
uuid: ec0c0541-395a-4647-8f77-54e96974e89c
>>>>>>> 0a3fac84826d2126349f1954e94f5ac86547d8df
langcode: en
status: true
dependencies:
  module:
    - system
  theme:
    - laujutheme
_core:
  default_config_hash: KHQIJ7Vfl25lTjzIc7qIvnuistt-Mw2O0kG4jCofmkI
id: laujutheme_messages
theme: laujutheme
region: header
weight: 0
provider: null
plugin: system_messages_block
settings:
  id: system_messages_block
  label: 'Status messages'
  provider: system
  label_display: '0'
visibility: {  }
