<<<<<<< HEAD
uuid: f086b061-0ced-4c0d-9861-cd9c18b82a95
=======
uuid: 56e8a7e7-875a-47b3-a9e7-f14b96c9a936
>>>>>>> 0a3fac84826d2126349f1954e94f5ac86547d8df
langcode: en
status: true
dependencies:
  module:
    - system
  theme:
    - laujutheme
_core:
  default_config_hash: jQQUUWN2Uxr5qZtc9zcJKBCxpKY8orN1u2HPqYYRQDI
id: laujutheme_powered
theme: laujutheme
region: header
weight: 10
provider: null
plugin: system_powered_by_block
settings:
  id: system_powered_by_block
  label: 'Powered by Drupal'
  provider: system
  label_display: '0'
visibility: {  }
